//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessClient.ServiceChess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Get", Namespace="http://schemas.datacontract.org/2004/07/ChessClient")]
    [System.SerializableAttribute()]
    public partial struct Get : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChessClient.ServiceChess.PieceColor colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChessClient.ServiceChess.PieceColor color {
            get {
                return this.colorField;
            }
            set {
                if ((this.colorField.Equals(value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PieceColor", Namespace="http://schemas.datacontract.org/2004/07/ChessClient")]
    public enum PieceColor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        White = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Black = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceChess.IServiceChess", CallbackContract=typeof(ChessClient.ServiceChess.IServiceChessCallback))]
    public interface IServiceChess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChess/Connect", ReplyAction="http://tempuri.org/IServiceChess/ConnectResponse")]
        ChessClient.ServiceChess.Get Connect(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChess/Connect", ReplyAction="http://tempuri.org/IServiceChess/ConnectResponse")]
        System.Threading.Tasks.Task<ChessClient.ServiceChess.Get> ConnectAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChess/Disconnect", ReplyAction="http://tempuri.org/IServiceChess/DisconnectResponse")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChess/Disconnect", ReplyAction="http://tempuri.org/IServiceChess/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/SendMsg")]
        void SendMsg(string msg, int id, int to);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/SendMsg")]
        System.Threading.Tasks.Task SendMsgAsync(string msg, int id, int to);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Move")]
        void Move(int id, int x1, int y1, int x2, int y2, int promote);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Move")]
        System.Threading.Tasks.Task MoveAsync(int id, int x1, int y1, int x2, int y2, int promote);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Surrender")]
        void Surrender(int id, int val);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Surrender")]
        System.Threading.Tasks.Task SurrenderAsync(int id, int val);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Ready")]
        void Ready(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Ready")]
        System.Threading.Tasks.Task ReadyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Draw")]
        void Draw(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Draw")]
        System.Threading.Tasks.Task DrawAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/CancelDraw")]
        void CancelDraw(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/CancelDraw")]
        System.Threading.Tasks.Task CancelDrawAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/UpdateColor")]
        void UpdateColor(int id, ChessClient.ServiceChess.PieceColor color);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/UpdateColor")]
        System.Threading.Tasks.Task UpdateColorAsync(int id, ChessClient.ServiceChess.PieceColor color);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChessCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/MsgCallback")]
        void MsgCallback(string msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/ChangeColor")]
        void ChangeColor(ChessClient.ServiceChess.PieceColor color);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/Start")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/DrawOffer")]
        void DrawOffer();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/DrawUser")]
        void DrawUser();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/MoveUser")]
        void MoveUser(int x1, int y1, int x2, int y2, int promote);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceChess/SurrenderUser")]
        void SurrenderUser(int val);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChessChannel : ChessClient.ServiceChess.IServiceChess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChessClient : System.ServiceModel.DuplexClientBase<ChessClient.ServiceChess.IServiceChess>, ChessClient.ServiceChess.IServiceChess {
        
        public ServiceChessClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceChessClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceChessClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChessClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChessClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ChessClient.ServiceChess.Get Connect(string name) {
            return base.Channel.Connect(name);
        }
        
        public System.Threading.Tasks.Task<ChessClient.ServiceChess.Get> ConnectAsync(string name) {
            return base.Channel.ConnectAsync(name);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public void SendMsg(string msg, int id, int to) {
            base.Channel.SendMsg(msg, id, to);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(string msg, int id, int to) {
            return base.Channel.SendMsgAsync(msg, id, to);
        }
        
        public void Move(int id, int x1, int y1, int x2, int y2, int promote) {
            base.Channel.Move(id, x1, y1, x2, y2, promote);
        }
        
        public System.Threading.Tasks.Task MoveAsync(int id, int x1, int y1, int x2, int y2, int promote) {
            return base.Channel.MoveAsync(id, x1, y1, x2, y2, promote);
        }
        
        public void Surrender(int id, int val) {
            base.Channel.Surrender(id, val);
        }
        
        public System.Threading.Tasks.Task SurrenderAsync(int id, int val) {
            return base.Channel.SurrenderAsync(id, val);
        }
        
        public void Ready(int id) {
            base.Channel.Ready(id);
        }
        
        public System.Threading.Tasks.Task ReadyAsync(int id) {
            return base.Channel.ReadyAsync(id);
        }
        
        public void Draw(int id) {
            base.Channel.Draw(id);
        }
        
        public System.Threading.Tasks.Task DrawAsync(int id) {
            return base.Channel.DrawAsync(id);
        }
        
        public void CancelDraw(int id) {
            base.Channel.CancelDraw(id);
        }
        
        public System.Threading.Tasks.Task CancelDrawAsync(int id) {
            return base.Channel.CancelDrawAsync(id);
        }
        
        public void UpdateColor(int id, ChessClient.ServiceChess.PieceColor color) {
            base.Channel.UpdateColor(id, color);
        }
        
        public System.Threading.Tasks.Task UpdateColorAsync(int id, ChessClient.ServiceChess.PieceColor color) {
            return base.Channel.UpdateColorAsync(id, color);
        }
    }
}
